#!/bin/bash
IMAGE_SIZE=224
ARCHITECTURE="mobilenet_0.50_${IMAGE_SIZE}"
HOME_DIR="/home/ana/Documents/PI/"

cd "${HOME_DIR}"Tensorflow/tensorflow-for-poets-2        
source ~/tensorflow/bin/activate 

python -m scripts.retrain \
  --bottleneck_dir=tf_files/bottlenecks \
  --how_many_training_steps=500 \
  --model_dir=tf_files/models/ \
  --summaries_dir=tf_files/training_summaries/"${ARCHITECTURE}" \
  --output_graph=tf_files/retrained_graph.pb \
  --output_labels=tf_files/retrained_labels.txt \
  --architecture="${ARCHITECTURE}" \
  --image_dir="${HOME_DIR}"Fotografias/Treino
